name: Docker CI & Push

on:
  push: {}  # für alle Branches

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2) QEMU & Buildx (Multi-Arch)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3) Login in GHCR
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4) Klein­schreibung des Repository-Owners
      - name: Define image namespace
        run: |
          echo "IMAGE_NAMESPACE=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # 5) Build & Push Backend-Image
      - name: Build & Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAMESPACE }}/nightcrawler-backend:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_NAMESPACE }}/nightcrawler-backend:latest

      # 6) Build & Push Frontend-Image
      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAMESPACE }}/nightcrawler-frontend:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_NAMESPACE }}/nightcrawler-frontend:latest

      # 7) (Optional) Start Test-Stack & Cleanup
      - name: Start Test Stack
        run: |
          docker-compose up -d
          # hier könnten Smoke-Tests folgen
          docker-compose down

      - name: Cleanup Local Docker
        run: docker system prune -af
